apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kalp-prod
  name: kalp-sdk-backend-prod-deployment
  labels:
    app: kalp-sdk-backend-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kalp-sdk-backend-prod
  template:
    metadata:
      labels:
        app: kalp-sdk-backend-prod
    spec:
      hostname: kalp-sdk-backend-prod
      automountServiceAccountToken: false
      containers:
      - name: kalp-sdk-backend-prod
        image: 408153089286.dkr.ecr.ap-south-1.amazonaws.com/kalp-sdk-backend-prod:<VERSION>
        imagePullPolicy: IfNotPresent     
        resources:
            requests:
              memory: "1024Mi"
              cpu: "500m"
            limits:
              memory: "2048Mi"
              cpu: "750m"                                       
        # readinessProbe:
        #     httpGet:
        #       path: /v1/healthcheck
        #       port: 3000
        #     initialDelaySeconds: 30
        #     timeoutSeconds: 10
        # livenessProbe:
        #     httpGet:
        #       path: /v1/healthcheck
        #       port: 3000
        #     initialDelaySeconds: 30
        #     periodSeconds: 5
        #     timeoutSeconds: 10
        #     failureThreshold: 4
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        # env:
        #   - name: PORT
        #     valueFrom:
        #       secretKeyRef:
        #         key: PORT
        #         name: prod-kalp-sdk 
---
apiVersion: v1
kind: Service
metadata:
  namespace: kalp-prod
  name: kalp-sdk-backend-prod-svc
  labels:
    svc: kalp-sdk-backend-prod
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: kalp-sdk-backend-prod
